# model type
model_str: "transformer"

# parameters for the transformer model

num_layers: 8
hidden_size: 123
num_heads: 7
dropout: 0.1

n_epochs: 10
batch_size: 1
learning_rate: 0.0001
weight_decay: 0.00

# session name
session_name: "session_1"