# model type
model_str: "mlp"

# parameters for the feedforward model
learning_rate: 0.001
weight_decay: 0.000
batch_size: 512
n_epochs: 1500
hidden_size: 1024

# session name
session_name: "session_1"
